[phases.setup]
nixPkgs = ["python3", "gcc", "pkg-config", "cairo", "pango", "gdk-pixbuf", "libffi"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv", ". /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT MAIN_APP:app"
